name: CI for Linter Checks using tox, isort, flake, ansible-lint


on: [workflow_call] # allow this workflow to be called from other workflows


jobs:
  linters:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    uses: ansible-network/github_actions/.github/workflows/tox.yml@main
    with:
      envname: ""
      labelname: "lint"
